//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBigDukan
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Registration
    {
        public string name { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string cellNo { get; set; }
        public string password { get; set; }
        public string userType { get; set; }
        public bool isActive { get; set; }
        public int id { get; set; }
        public string time { get; set; }
        public string Image { get; set; }
        public HttpPostedFileBase Image_new { get; set; }
    }
}
